//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImagePalettePageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagePalettePageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Pages.ImagePalettePageStrings", typeof(ImagePalettePageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置自动提取颜色数： 的本地化字符串。
        /// </summary>
        internal static string AutoColorsCountSetting_Header {
            get {
                return ResourceManager.GetString("AutoColorsCountSetting.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动提取 的本地化字符串。
        /// </summary>
        internal static string AutoColorsList_Title {
            get {
                return ResourceManager.GetString("AutoColorsList.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动提取 的本地化字符串。
        /// </summary>
        internal static string AutoExtractButton_Text {
            get {
                return ResourceManager.GetString("AutoExtractButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关手动像素颜色提取 的本地化字符串。
        /// </summary>
        internal static string ColorPickerToggleButton_Tooltip {
            get {
                return ResourceManager.GetString("ColorPickerToggleButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空列表 的本地化字符串。
        /// </summary>
        internal static string ColorsListClearButton_Tooltip {
            get {
                return ResourceManager.GetString("ColorsListClearButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适应面板大小 的本地化字符串。
        /// </summary>
        internal static string FitSizeButton_Tooltip {
            get {
                return ResourceManager.GetString("FitSizeButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从&quot;{0}&quot; 提取的调色板 的本地化字符串。
        /// </summary>
        internal static string ImagePaletteDescription {
            get {
                return ResourceManager.GetString("ImagePaletteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动提取 的本地化字符串。
        /// </summary>
        internal static string ManualColorsList_Title {
            get {
                return ResourceManager.GetString("ManualColorsList.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string ZoomInButton_Tooltip {
            get {
                return ResourceManager.GetString("ZoomInButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string ZoomOutButton_Tooltip {
            get {
                return ResourceManager.GetString("ZoomOutButton.Tooltip", resourceCulture);
            }
        }
    }
}
