//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaletteDetailPageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaletteDetailPageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Pages.PaletteDetailPageStrings", typeof(PaletteDetailPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加颜色 的本地化字符串。
        /// </summary>
        internal static string AddColorButton_Tooltip {
            get {
                return ResourceManager.GetString("AddColorButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回至 {0} 的本地化字符串。
        /// </summary>
        internal static string BackToFolderButton_Text {
            get {
                return ResourceManager.GetString("BackToFolderButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭侧栏 的本地化字符串。
        /// </summary>
        internal static string CloseColorEditPaneButton_Tooltip {
            get {
                return ResourceManager.GetString("CloseColorEditPaneButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（点击以编辑颜色） 的本地化字符串。
        /// </summary>
        internal static string ColorItem_Tooltip {
            get {
                return ResourceManager.GetString("ColorItem.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [未命名] 的本地化字符串。
        /// </summary>
        internal static string ColorName_Placeholder {
            get {
                return ResourceManager.GetString("ColorName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（点击以编辑颜色名称） 的本地化字符串。
        /// </summary>
        internal static string ColorName_Tooltip {
            get {
                return ResourceManager.GetString("ColorName.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（点击以复制到剪切板） 的本地化字符串。
        /// </summary>
        internal static string ColorValueButton_Tooltip {
            get {
                return ResourceManager.GetString("ColorValueButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板 的本地化字符串。
        /// </summary>
        internal static string DeletePaletteButton_Text {
            get {
                return ResourceManager.GetString("DeletePaletteButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出调色板（目前仅支持 ACO 文件） 的本地化字符串。
        /// </summary>
        internal static string ExportPaletteButton_Tooltip {
            get {
                return ResourceManager.GetString("ExportPaletteButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看更多调色板的操作 的本地化字符串。
        /// </summary>
        internal static string MoreActionsButton_Tooltip {
            get {
                return ResourceManager.GetString("MoreActionsButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述... 的本地化字符串。
        /// </summary>
        internal static string PaletteDescription_Placeholder {
            get {
                return ResourceManager.GetString("PaletteDescription.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（点击以编辑描述） 的本地化字符串。
        /// </summary>
        internal static string PaletteDescription_Tooltip {
            get {
                return ResourceManager.GetString("PaletteDescription.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色板标题... 的本地化字符串。
        /// </summary>
        internal static string PaletteTitle_Placeholder {
            get {
                return ResourceManager.GetString("PaletteTitle.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}（点击以编辑调色板标题） 的本地化字符串。
        /// </summary>
        internal static string PaletteTitle_Tooltip {
            get {
                return ResourceManager.GetString("PaletteTitle.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换选择模式 的本地化字符串。
        /// </summary>
        internal static string ToggleSelectionModeButton_Tooltip {
            get {
                return ResourceManager.GetString("ToggleSelectionModeButton.Tooltip", resourceCulture);
            }
        }
    }
}
