//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsPageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Pages.SettingsPageStrings", typeof(SettingsPageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观和行为 的本地化字符串。
        /// </summary>
        internal static string AppearanceAndBehavior {
            get {
                return ResourceManager.GetString("AppearanceAndBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色模式 的本地化字符串。
        /// </summary>
        internal static string AppTheme_Dark {
            get {
                return ResourceManager.GetString("AppTheme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择应用的颜色模式 的本地化字符串。
        /// </summary>
        internal static string AppTheme_Description {
            get {
                return ResourceManager.GetString("AppTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string AppTheme_Header {
            get {
                return ResourceManager.GetString("AppTheme.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色模式 的本地化字符串。
        /// </summary>
        internal static string AppTheme_Light {
            get {
                return ResourceManager.GetString("AppTheme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 默认 的本地化字符串。
        /// </summary>
        internal static string AppTheme_System {
            get {
                return ResourceManager.GetString("AppTheme.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢以下开源项目和库的支持与贡献 的本地化字符串。
        /// </summary>
        internal static string DependenciesAndReferences_Description {
            get {
                return ResourceManager.GetString("DependenciesAndReferences.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖和参考 的本地化字符串。
        /// </summary>
        internal static string DependenciesAndReferences_Header {
            get {
                return ResourceManager.GetString("DependenciesAndReferences.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转至 RemeaMiku 的个人主页 的本地化字符串。
        /// </summary>
        internal static string Developer_ActionTooltip {
            get {
                return ResourceManager.GetString("Developer.ActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以世界为大学校，以天然和人事为教科书。.NET 开发者/画手 的本地化字符串。
        /// </summary>
        internal static string Developer_Description {
            get {
                return ResourceManager.GetString("Developer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemeaMiku 的本地化字符串。
        /// </summary>
        internal static string Developer_Header {
            get {
                return ResourceManager.GetString("Developer.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若不支持 Windows 语言，应用将会使用英语。需要重启应用后生效 的本地化字符串。
        /// </summary>
        internal static string Language_Description {
            get {
                return ResourceManager.GetString("Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string Language_enUS {
            get {
                return ResourceManager.GetString("Language.enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language_Header {
            get {
                return ResourceManager.GetString("Language.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        internal static string Language_jaJP {
            get {
                return ResourceManager.GetString("Language.jaJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 默认 的本地化字符串。
        /// </summary>
        internal static string Language_System {
            get {
                return ResourceManager.GetString("Language.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string Language_zhCN {
            get {
                return ResourceManager.GetString("Language.zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择导航栏的位置 的本地化字符串。
        /// </summary>
        internal static string NavigationStyle_Description {
            get {
                return ResourceManager.GetString("NavigationStyle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航样式 的本地化字符串。
        /// </summary>
        internal static string NavigationStyle_Header {
            get {
                return ResourceManager.GetString("NavigationStyle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧 的本地化字符串。
        /// </summary>
        internal static string NavigationStyle_Left {
            get {
                return ResourceManager.GetString("NavigationStyle.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        internal static string NavigationStyle_Top {
            get {
                return ResourceManager.GetString("NavigationStyle.Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要重启应用以生效 的本地化字符串。
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
