//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.Maui.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.Maui.Resources.Globalization.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 为调色板添加说明 的本地化字符串。
        /// </summary>
        internal static string AddDescriptionsForPalette {
            get {
                return ResourceManager.GetString("AddDescriptionsForPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新颜色 的本地化字符串。
        /// </summary>
        internal static string AddNewColor {
            get {
                return ResourceManager.GetString("AddNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新调色板 的本地化字符串。
        /// </summary>
        internal static string AddNewPalette {
            get {
                return ResourceManager.GetString("AddNewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击以修改说明 的本地化字符串。
        /// </summary>
        internal static string ClickToEditDescription {
            get {
                return ResourceManager.GetString("ClickToEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击以重命名 的本地化字符串。
        /// </summary>
        internal static string ClickToRename {
            get {
                return ResourceManager.GetString("ClickToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭颜色详情面板 的本地化字符串。
        /// </summary>
        internal static string CloseColorDetailPanel {
            get {
                return ResourceManager.GetString("CloseColorDetailPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制 的本地化字符串。
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到剪切板 的本地化字符串。
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除颜色 的本地化字符串。
        /// </summary>
        internal static string DeleteColor {
            get {
                return ResourceManager.GetString("DeleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此调色板 的本地化字符串。
        /// </summary>
        internal static string DeletePalette {
            get {
                return ResourceManager.GetString("DeletePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除调色板 “{0}” 吗？ 的本地化字符串。
        /// </summary>
        internal static string DeletePaletteDialogMessage {
            get {
                return ResourceManager.GetString("DeletePaletteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板 的本地化字符串。
        /// </summary>
        internal static string DeletePalettes {
            get {
                return ResourceManager.GetString("DeletePalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除这 {0} 个调色板吗？ 的本地化字符串。
        /// </summary>
        internal static string DeletePalettesDialogMessage {
            get {
                return ResourceManager.GetString("DeletePalettesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mirai Palette 的本地化字符串。
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新颜色 的本地化字符串。
        /// </summary>
        internal static string NewColor {
            get {
                return ResourceManager.GetString("NewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新调色板 的本地化字符串。
        /// </summary>
        internal static string NewPalette {
            get {
                return ResourceManager.GetString("NewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色板 的本地化字符串。
        /// </summary>
        internal static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色板一览 的本地化字符串。
        /// </summary>
        internal static string Palettes {
            get {
                return ResourceManager.GetString("Palettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要移除颜色 “{0}” 吗？ 的本地化字符串。
        /// </summary>
        internal static string RemoveColorDialogMessage {
            get {
                return ResourceManager.GetString("RemoveColorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关选择模式 的本地化字符串。
        /// </summary>
        internal static string ToggleSelectionMode {
            get {
                return ResourceManager.GetString("ToggleSelectionMode", resourceCulture);
            }
        }
    }
}
