//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.Maui.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.Maui.Resources.Globalization.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   为调色板添加说明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddDescriptionsForPalette {
            get {
                return ResourceManager.GetString("AddDescriptionsForPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添加新颜色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddNewColor {
            get {
                return ResourceManager.GetString("AddNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添加新调色板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddNewPalette {
            get {
                return ResourceManager.GetString("AddNewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单击以修改说明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClickToEditDescription {
            get {
                return ResourceManager.GetString("ClickToEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单击以重命名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClickToRename {
            get {
                return ResourceManager.GetString("ClickToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   关闭颜色详情面板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseColorDetailPanel {
            get {
                return ResourceManager.GetString("CloseColorDetailPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   颜色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   确定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   已复制 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   复制到剪切板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   删除颜色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteColor {
            get {
                return ResourceManager.GetString("DeleteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   删除此调色板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletePalette {
            get {
                return ResourceManager.GetString("DeletePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   你确定要删除调色板 “{0}” 吗？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletePaletteDialogMessage {
            get {
                return ResourceManager.GetString("DeletePaletteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   删除调色板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletePalettes {
            get {
                return ResourceManager.GetString("DeletePalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   你确定要删除这 {0} 个调色板吗？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletePalettesDialogMessage {
            get {
                return ResourceManager.GetString("DeletePalettesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   说明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   首页 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   语言 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mirai Palette に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新颜色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewColor {
            get {
                return ResourceManager.GetString("NewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新调色板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewPalette {
            get {
                return ResourceManager.GetString("NewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   调色板 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   调色板一览 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Palettes {
            get {
                return ResourceManager.GetString("Palettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   你确定要移除颜色 “{0}” 吗？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveColorDialogMessage {
            get {
                return ResourceManager.GetString("RemoveColorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全选 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   开关选择模式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToggleSelectionMode {
            get {
                return ResourceManager.GetString("ToggleSelectionMode", resourceCulture);
            }
        }
    }
}
