// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiraiPalette.Shared.Data;

#nullable disable

namespace MiraiPalette.Shared.Migrations
{
    [DbContext(typeof(MiraiPaletteDb))]
    [Migration("20250820012325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MiraiPalette.Shared.Entities.MiraiColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MiraiPaletteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaletteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MiraiPaletteId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("MiraiPalette.Shared.Entities.MiraiPalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("MiraiPalette.Shared.Entities.MiraiColor", b =>
                {
                    b.HasOne("MiraiPalette.Shared.Entities.MiraiPalette", null)
                        .WithMany("Colors")
                        .HasForeignKey("MiraiPaletteId");
                });

            modelBuilder.Entity("MiraiPalette.Shared.Entities.MiraiPalette", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
