//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加颜色 的本地化字符串。
        /// </summary>
        internal static string AddColor_Tooltip {
            get {
                return ResourceManager.GetString("AddColor.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部调色板 的本地化字符串。
        /// </summary>
        internal static string AllPalettes {
            get {
                return ResourceManager.GetString("AllPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除选择 的本地化字符串。
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建空白调色板 的本地化字符串。
        /// </summary>
        internal static string CreateNewPalette_Tooltip {
            get {
                return ResourceManager.GetString("CreateNewPalette.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板 的本地化字符串。
        /// </summary>
        internal static string DeletePalettes {
            get {
                return ResourceManager.GetString("DeletePalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取 的本地化字符串。
        /// </summary>
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从图片中提取 的本地化字符串。
        /// </summary>
        internal static string ExtractPaletteFromImage_Tooltip {
            get {
                return ResourceManager.GetString("ExtractPaletteFromImage.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件导入（目前只支持ACO文件） 的本地化字符串。
        /// </summary>
        internal static string ImportPaletteFile_Tooltip {
            get {
                return ResourceManager.GetString("ImportPaletteFile.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选 的本地化字符串。
        /// </summary>
        internal static string MultipleSelection {
            get {
                return ResourceManager.GetString("MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建调色板 的本地化字符串。
        /// </summary>
        internal static string NewPalette {
            get {
                return ResourceManager.GetString("NewPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击以编辑调色板标题 的本地化字符串。
        /// </summary>
        internal static string PaletteDescription_Tooltip {
            get {
                return ResourceManager.GetString("PaletteDescription_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击以编辑调色板描述 的本地化字符串。
        /// </summary>
        internal static string PaletteTitle_Tooltip {
            get {
                return ResourceManager.GetString("PaletteTitle_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除颜色 的本地化字符串。
        /// </summary>
        internal static string RemoveColor {
            get {
                return ResourceManager.GetString("RemoveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换选择模式 的本地化字符串。
        /// </summary>
        internal static string ToggleSelectionMode_Tooltip {
            get {
                return ResourceManager.GetString("ToggleSelectionMode.Tooltip", resourceCulture);
            }
        }
    }
}
