//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeleteConfirmStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeleteConfirmStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Dialogs.DeleteConfirmStrings", typeof(DeleteConfirmStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要删除所有自动提取的颜色吗？ 的本地化字符串。
        /// </summary>
        internal static string AutoColorListClear_Message {
            get {
                return ResourceManager.GetString("AutoColorListClear.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空自动提取 的本地化字符串。
        /// </summary>
        internal static string AutoColorListClear_Title {
            get {
                return ResourceManager.GetString("AutoColorListClear.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要删除所有手动提取的颜色吗？ 的本地化字符串。
        /// </summary>
        internal static string ManualColorListClear_Message {
            get {
                return ResourceManager.GetString("ManualColorListClear.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空手动提取 的本地化字符串。
        /// </summary>
        internal static string ManualColorListClear_Title {
            get {
                return ResourceManager.GetString("ManualColorListClear.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要移除所选的 {0} 个颜色吗？ 的本地化字符串。
        /// </summary>
        internal static string MultipleColors_Message {
            get {
                return ResourceManager.GetString("MultipleColors.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除颜色 的本地化字符串。
        /// </summary>
        internal static string MultipleColors_Title {
            get {
                return ResourceManager.GetString("MultipleColors.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要删除所选的 {0} 个调色板吗？ 的本地化字符串。
        /// </summary>
        internal static string MultiplePalettes_Message {
            get {
                return ResourceManager.GetString("MultiplePalettes.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板 的本地化字符串。
        /// </summary>
        internal static string MultiplePalettes_Title {
            get {
                return ResourceManager.GetString("MultiplePalettes.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要移除颜色“{0}”吗？ 的本地化字符串。
        /// </summary>
        internal static string SingleColor_Message {
            get {
                return ResourceManager.GetString("SingleColor.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除颜色 的本地化字符串。
        /// </summary>
        internal static string SingleColor_Title {
            get {
                return ResourceManager.GetString("SingleColor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要删除调色板“{0}”吗？ 的本地化字符串。
        /// </summary>
        internal static string SinglePalette_Message {
            get {
                return ResourceManager.GetString("SinglePalette.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板 的本地化字符串。
        /// </summary>
        internal static string SinglePalette_Title {
            get {
                return ResourceManager.GetString("SinglePalette.Title", resourceCulture);
            }
        }
    }
}
