//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiPalette.WinUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiPalette.WinUI.Strings.Dialogs.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹时发生错误 的本地化字符串。
        /// </summary>
        internal static string AddFolder_Error {
            get {
                return ResourceManager.GetString("AddFolder.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹失败 的本地化字符串。
        /// </summary>
        internal static string AddFolder_Title {
            get {
                return ResourceManager.GetString("AddFolder.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前有正在进行的操作，请稍后重试。 的本地化字符串。
        /// </summary>
        internal static string AppIsBusy_Retry {
            get {
                return ResourceManager.GetString("AppIsBusy.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后 的本地化字符串。
        /// </summary>
        internal static string AppIsBusy_Title {
            get {
                return ResourceManager.GetString("AppIsBusy.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建调色板时发生错误。 的本地化字符串。
        /// </summary>
        internal static string CreatePalette_Error {
            get {
                return ResourceManager.GetString("CreatePalette.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建调色板失败 的本地化字符串。
        /// </summary>
        internal static string CreatePalette_Title {
            get {
                return ResourceManager.GetString("CreatePalette.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹时发生错误。 的本地化字符串。
        /// </summary>
        internal static string DeleteFolder_Error {
            get {
                return ResourceManager.GetString("DeleteFolder.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹失败 的本地化字符串。
        /// </summary>
        internal static string DeleteFolder_Title {
            get {
                return ResourceManager.GetString("DeleteFolder.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板时发生错误。 的本地化字符串。
        /// </summary>
        internal static string DeleteMultiplePalettes_Error {
            get {
                return ResourceManager.GetString("DeleteMultiplePalettes.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板失败 的本地化字符串。
        /// </summary>
        internal static string DeleteMultiplePalettes_Title {
            get {
                return ResourceManager.GetString("DeleteMultiplePalettes.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板时发生错误 的本地化字符串。
        /// </summary>
        internal static string DeleteSinglePalette_Error {
            get {
                return ResourceManager.GetString("DeleteSinglePalette.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除调色板失败 的本地化字符串。
        /// </summary>
        internal static string DeleteSinglePalette_Title {
            get {
                return ResourceManager.GetString("DeleteSinglePalette.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出调色板至文件时发生错误。请检查文件路径或权限后重试。 的本地化字符串。
        /// </summary>
        internal static string ExportPaletteFile_Error {
            get {
                return ResourceManager.GetString("ExportPaletteFile.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出调色板失败 的本地化字符串。
        /// </summary>
        internal static string ExportPaletteFile_Title {
            get {
                return ResourceManager.GetString("ExportPaletteFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入调色板文件时发生错误。请检查文件路径或权限后重试。 的本地化字符串。
        /// </summary>
        internal static string ImportPaletteFile_Error {
            get {
                return ResourceManager.GetString("ImportPaletteFile.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色板文件格式不支持或文件为空。 的本地化字符串。
        /// </summary>
        internal static string ImportPaletteFile_Failed {
            get {
                return ResourceManager.GetString("ImportPaletteFile.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入调色板失败 的本地化字符串。
        /// </summary>
        internal static string ImportPaletteFile_Title {
            get {
                return ResourceManager.GetString("ImportPaletteFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载数据时发生错误。 的本地化字符串。
        /// </summary>
        internal static string LoadData_Error {
            get {
                return ResourceManager.GetString("LoadData.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据加载失败 的本地化字符串。
        /// </summary>
        internal static string LoadData_Title {
            get {
                return ResourceManager.GetString("LoadData.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径&quot;{0}&quot;不存在。 的本地化字符串。
        /// </summary>
        internal static string PathNotExists {
            get {
                return ResourceManager.GetString("PathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新文件夹时发生错误。 的本地化字符串。
        /// </summary>
        internal static string UpdateFolder_Error {
            get {
                return ResourceManager.GetString("UpdateFolder.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新文件夹失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFolder_Title {
            get {
                return ResourceManager.GetString("UpdateFolder.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新调色板时发生错误。 的本地化字符串。
        /// </summary>
        internal static string UpdatePalette_Error {
            get {
                return ResourceManager.GetString("UpdatePalette.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新调色板失败 的本地化字符串。
        /// </summary>
        internal static string UpdatePalette_Title {
            get {
                return ResourceManager.GetString("UpdatePalette.Title", resourceCulture);
            }
        }
    }
}
